# Generated by Django 5.2 on 2025-04-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeRequest',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
