# Generated by Django 5.2 on 2025-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0002_remove_userprofile_user_delete_employeerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=10),
        ),
    ]
