# Generated by Django 5.2 on 2025-04-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0003_inventario_stock_minimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_lavado',
        ),
        migrations.AddField(
            model_name='servicio',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='secciones.cita'),
        ),
    ]
